config/routes.rb
Rails.application.routes.draw do
  get 'ratings/create'
  get 'ratings/update'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    namespace :admin do
      resources :categories
      resources :albums
      resources :songs do
        get "/get_approve", to: "lyric_requests#get_approve"
        resources :lyric_requests, only: :update
      end
      resources :lyric_requests, only: %i(index update)
    end
    resources :categories, only: :index
    resources :albums, only: %i(index show)
    resources :songs, only: %i(index show) do
      resources :comments
      resources :favorite_songs, only: %i(create destroy)
      resources :ratings
      resources :lyric_requests, only: %i(create edit update)
    end
    resources :favorite_songs, only: :index
    devise_for :users
  end
end

app/models/favorite_song.rb
class FavoriteSong < ApplicationRecord
  ATTR_PARAMS = %i(user_id song_id)
  belongs_to :song
  belongs_to :user
end

app/controllers/favorite_songs_controller.rb
class FavoriteSongsController < ApplicationController
  before_action :load_song, :load_favorite_song, only: %i(create destroy)

  def index
    @favorite_songs = current_user.favorite_songs.includes(:song)
  end

  def create
    @favorite_song = current_user.favorite_songs.build fs_params
    unless @favorite_song.save
      flash.now[:danger] = t "admin.favorite_songs.create.fail"
    end
    respond_to :js
  end

  def destroy
    unless @favorite_song.destroy
      flash.now[:danger] = t "admin.favorite_songs.destroy.fail"
    end
    respond_to :js
  end

  private

  def fs_params
    params.require(:favorite_song).permit FavoriteSong::ATTR_PARAMS
  end

  def load_favorite_song
    @favorite_song = @song.favorite_songs.find_by id: params[:id]
    return if @favorite_song

    flash.now[:danger] = t "admin.favorite_songs.not_found_fs"
    respond_to :js
  end

  def load_song
    @song = Song.find_by id: params[:song_id]
    return if @song

    flash[:danger] = t "admin.songs.not_found_song"
    redirect_to songs_path
  end
end

app/helpers/favorite_songs_helper.rb
module FavoriteSongsHelper
  def load_fs song
    current_user.favorite_songs.find_by song_id: song.id
  end
end

app/views/favorite_songs/_dislike.html.erb
<%= form_for [@song, load_fs(@song)], html: { method: :delete }, remote: true do |f| %>
  <%= f.button :submit, class: "btn btn-secondary" do %>
    <i class="fas fa-heart-broken"></i>
  <% end %>
<% end %>

app/views/favorite_songs/_favorite_song.html.erb
<tr>
  <td><%= link_to favorite_song.song.name, song_path(favorite_song.song) %></td>
  <td><%= favorite_song.song.category.name %></td>
  <td><%= l favorite_song.song.created_at, format: :long %></td>
</tr>

app/views/favorite_songs/_like.html.erb
<%= form_for [@song, @favorite_song || @song.favorite_songs.build], remote: true do |f| %>
  <div>  <%= f.hidden_field :song_id, value: @song.id %></div>
  <%= f.button :submit, class: "btn btn-danger" do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% end %>

app/views/favorite_songs/_like_form.html.erb
<div id="like_form">
  <% if @song.favorite? current_user %>
    <%= render "favorite_songs/dislike", song: @song, favorite_song: @favorite_song %>
  <% else %>
    <%= render "favorite_songs/like", song: @song, favorite_song: @favorite_song %>
  <% end %>
</div>

app/views/favorite_songs/create.js.erb
$("#like_form").html('<%= j render "favorite_songs/dislike" %>');

app/views/favorite_songs/destroy.js.erb
$("#like_form").html('<%= j render "favorite_songs/like" %>');

app/views/favorite_songs/index.html.erb
<div class="container">
  <h2><%= t "layouts.header.my_song" %></h2>
  <table class="table table-hover">
    <thead>
    <tr>
      <th><%= t "layouts.header.name" %></th>
      <th><%= t "layouts.header.category" %></th>
      <th><%= t "layouts.header.created_h" %></th>
    </tr>
    </thead>
    <tbody class = "song_tbody_content">
    <%= render(@favorite_songs) || t("admin.songs.no_song") %>
    </tbody>
  </table>
</div>