config/routes.rb
Rails.application.routes.draw do
  get 'ratings/create'
  get 'ratings/update'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    namespace :admin do
      resources :categories
      resources :albums
      resources :songs do
        get "/get_approve", to: "lyric_requests#get_approve"
        resources :lyric_requests, only: :update
      end
      resources :lyric_requests, only: %i(index update)
    end
    resources :categories, only: :index
    resources :albums, only: %i(index show)
    resources :songs, only: %i(index show) do
      resources :comments
      resources :favorite_songs, only: %i(create destroy)
      resources :ratings
      resources :lyric_requests, only: %i(create edit update)
    end
    resources :favorite_songs, only: :index
    devise_for :users
  end
end

app/models/lyric_request.rb
class LyricRequest < ApplicationRecord
  ATTR_PARAMS = %i(lyric_detail status user_id song_id)
  belongs_to :song
  belongs_to :user
  enum status: {unapprove: 0, approved: 1, approved_show: 2}

  scope :is_unapprove, ->{where("status = ?", 0)}
  scope :is_show, ->(song_id) {where("status = ? and song_id = ?", 2, song_id)}
end

app/controllers/admin/lyric_requests_controller.rb
class Admin::LyricRequestsController < Admin::BaseController
  before_action :load_song, only: %i(update get_approve)
  before_action :load_lyric, only: :update

  def index
    @lyric_requests = LyricRequest.is_unapprove.select("distinct on (song_id) *")
  end

  def update
    return if LyricRequest.statuses.include? lyric_params[:status].to_i
    if @lyric_request.update_attributes status: lyric_params[:status].to_i
      flash[:success] = "Updated lyric for this song"
      redirect_to admin_song_get_approve_path(@song)
    else
      flash[:danger] = "Cannot update lyric for this song"
    end
  end

  def get_approve
    @lyric_requests = LyricRequest.where("song_id = ?", params[:song_id])
  end

  private

  def lyric_params
    params.require(:lyric_request).permit LyricRequest::ATTR_PARAMS
  end

  def load_song
    @song = Song.find_by id: params[:song_id]
    return if @song

    flash[:danger] = t "admin.songs.not_found_song"
    redirect_to songs_path
  end

  def load_lyric
    @lyric_request = LyricRequest.find_by id: params[:id]
    return if @lyric_request

    flash[:danger] = t "lyrics.not_found_lyric"
    redirect_to songs_path
  end
end

app/controllers/lyric_requests_controller.rb
class LyricRequestsController < ApplicationController
  before_action :load_song, only: %i(create update)
  before_action :load_lyric, only: %i(show update)

  def show; end

  def create
    @lyric_request = current_user.lyric_requests.build lyric_params
    if @lyric_request.save
      flash.now[:success] = t "lyrics.create.success"
    else
      flash.now[:danger] = t "lyrics.create.fail"
    end
    respond_to :js
  end

  def update
    if @lyric_request.update lyric_params
      @lyric_request.unapprove!
      flash.now[:success] = t "lyrics.update.success"
    else
      flash.now[:danger] = t "lyrics.update.fail"
    end
    respond_to :js
  end

  private

  def lyric_params
    params.require(:lyric_request).permit LyricRequest::ATTR_PARAMS
  end

  def load_song
    @song = Song.find_by id: params[:song_id]
    return if @song

    flash[:danger] = t "admin.songs.not_found_song"
    redirect_to songs_path
  end

  def load_lyric
    @lyric_request = current_user.lyric_requests.find_by id: params[:id]
    return if @lyric_request

    flash[:danger] = t "lyrics.not_found_lyric"
    redirect_to songs_path
  end
end

app/helpers/lyric_requests_helper.rb
module LyricRequestsHelper
  def load_lyric song
    LyricRequest.is_show(song.id).first
  end
end

app/views/admin/lyric_requests/_form_approve.html.erb
<%= form_for lr, url: admin_song_lyric_request_path(@song, lr), method: :patch do |f| %>
  <li>
    Contribute by <b><%= lr.user.name %></b> --
    <% case lr.status %>
    <% when "unapprove" %>
      <i class = "fas fa-times"></i>
    <% when "approved" %>
      <i class = "fas fa-check"></i>
    <% when "approved_show" %>
      <i class = "fas fa-check-double"></i>
    <% else %>
    <% end %>
    <br>
    <p style="border-style: solid; border-color: crimson"><%= lr.lyric_detail.html_safe %></p>
  </li>
  <%= f.select :status, options_for_select(LyricRequest.statuses, LyricRequest.statuses[lr.status]) %>
  <%= f.submit %>
<% end %>

app/views/admin/lyric_requests/_lyric_request.html.erb
<ul>
  <li>
    <%= link_to lyric_request.song.name, admin_song_get_approve_path(lyric_request.song) %>
  </li>
</ul>

app/views/admin/lyric_requests/get_approve.html.erb
<h2><%= @song.name %></h2>
<% @lyric_requests.each do |lr| %>
  <ul>
    <%= render "form_approve", lr: lr %>
  </ul>
  <hr>
<% end %>

app/views/admin/lyric_requests/index.html.erb
<%= render @lyric_requests %>