config/routes.rb
Rails.application.routes.draw do
  get 'ratings/create'
  get 'ratings/update'
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :account_activations, only: :edit
    namespace :admin do
      resources :categories
      resources :albums
      resources :songs do
        get "/get_approve", to: "lyric_requests#get_approve"
        resources :lyric_requests, only: :update
      end
      resources :lyric_requests, only: %i(index update)
    end
    resources :categories, only: :index
    resources :albums, only: %i(index show)
    resources :songs, only: %i(index show) do
      resources :comments
      resources :favorite_songs, only: %i(create destroy)
      resources :ratings
      resources :lyric_requests, only: %i(create edit update)
    end
    resources :favorite_songs, only: :index
    devise_for :users
  end
end

app/models/category.rb
class Category < ApplicationRecord
  ATTR_PARAMS = :name

  self.per_page = Settings.categories.per_page

  has_many :songs, dependent: :destroy

  scope :sort_by_name, -> {order name: :asc}

  validates :name, presence: true, length: { in: Settings.categories.name_length_min..Settings.categories.name_length_max }, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :load_category, except: %i(index new create)

  def index
    @categories = Category.sort_by_name.paginate page: params[:page]
  end

  def new
    @category = Category.new
  end

  def edit; end

  def show; end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t ".fail"
      render :new
    end
  end

  def update
    if @category.update category_params
      flash[:success] = t ".success"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t ".fail"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t ".success"
    else
      flash[:danger] = t ".fail"
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit Category::ATTR_PARAMS
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category

    flash[:danger] = t ".not_found_cat"
    redirect_to admin_categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.sort_by_name.paginate page: params[:page]
  end

  def show; end
end

app/views/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= l category.created_at, format: :long %></td>
  <td><%= l category.updated_at, format: :long %></td>
</tr>

app/views/categories/_form.html.erb
<%= form_for category do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/categories/index.html.erb
<div class="container">
  <h2><%= t "layouts.header.category" %></h2>
  <% if current_user.admin? %>
    <%= link_to t("layouts.header.new_btn"), new_category_path, class: "btn btn-info" %>
  <% end %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t "layouts.header.name" %></th>
        <th><%= t "layouts.header.created_h" %></th>
        <th><%= t "layouts.header.updated_h" %></th>
      </tr>
    </thead>
    <tbody>
      <%= will_paginate @categories %>
      <%= render(@categories) || t("categories.no_cat") %>
    </tbody>
  </table>
</div>